name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout el código
      uses: actions/checkout@v4

    - name: Configurar Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Dar permisos de ejecución a Gradlew
      run: chmod +x gradlew

    - name: Compilar APK de Debug
      run: ./gradlew assembleDebug

    - name: Subir el APK generado
      uses: actions/upload-artifact@v4
      with:
        name: MeeGo-Launcher-Debug
        path: app/build/outputs/apk/debug/app-debug.apk
